In [1]:
print("hello numpy")

hello numpy

In [4]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "Salary": [50000, 60000, 70000]
}

df = pd.DataFrame(data)
print (df)

   Name  Salary
0   Ali   50000
1  Sara   60000
2  John   70000

In [6]:
df['Bonus']= df['Salary']*2
print(df)

   Name  Salary   Bonus
0   Ali   50000  100000
1  Sara   60000  120000
2  John   70000  140000

In [7]:
import pandas as pd

data = {
    "Hours_Study": [2, 4, 6, 8, None],
    "Attendance": [60, 70, 80, 90, 85],
    "Pass": ["No", "No", "Yes", "Yes", "Yes"]
}

df = pd.DataFrame(data)

print(df)

   Hours_Study  Attendance Pass
0          2.0          60   No
1          4.0          70   No
2          6.0          80  Yes
3          8.0          90  Yes
4          NaN          85  Yes

In [8]:
df.isnull()

   Hours_Study  Attendance   Pass
0        False       False  False
1        False       False  False
2        False       False  False
3        False       False  False
4         True       False  False

In [9]:
df.isnull().sum()

Hours_Study    1
Attendance     0
Pass           0
dtype: int64

In [10]:
df.dropna()

   Hours_Study  Attendance Pass
0          2.0          60   No
1          4.0          70   No
2          6.0          80  Yes
3          8.0          90  Yes

In [11]:
df["Hours_Study"].fillna(df["Hours_Study"].mean())

0    2.0
1    4.0
2    6.0
3    8.0
4    5.0
Name: Hours_Study, dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Hours_Study  4 non-null      float64
 1   Attendance   5 non-null      int64
 2   Pass         5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes

In [13]:
df.describe()

       Hours_Study  Attendance
count     4.000000    5.000000
mean      5.000000   77.000000
std       2.581989   12.041595
min       2.000000   60.000000
25%       3.500000   70.000000
50%       5.000000   80.000000
75%       6.500000   85.000000
max       8.000000   90.000000

In [16]:
df.sort_values("Attendance",ascending= False)

   Hours_Study  Attendance Pass
3          8.0          90  Yes
4          NaN          85  Yes
2          6.0          80  Yes
1          4.0          70   No
0          2.0          60   No

In [17]:
df["Attendance"].value_counts()

Attendance
60    1
70    1
80    1
90    1
85    1
Name: count, dtype: int64

In [19]:
df["Attendance"].unique()

array([60, 70, 80, 90, 85])

In [20]:
df["Attendance"].nunique()

5

In [21]:
import pandas as pd

data = {
    "Customer": ["Rahim", "Karim", "Sakib"],
    "City": ["Dhaka", "Sylhet", "Chittagong"]
}

df = pd.DataFrame(data)

print(df)

  Customer        City
0    Rahim       Dhaka
1    Karim      Sylhet
2    Sakib  Chittagong

In [ ]:
df2 = pd.get_dummies(df["City"], dtype=int)

In [4]:
print(df2)

NameError: name 'df2' is not defined

In [5]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John"],
    "City": ["Dhaka", "Chittagong", "Dhaka"]
}

df = pd.DataFrame(data)

df2 = pd.get_dummies(df["City"], dtype=int)

print(df2)

   Chittagong  Dhaka
0           0      1
1           1      0
2           0      1

In [7]:
import pandas as pd

data = {
    "Food": ["Burger", "Pizza", "Burger", "Pasta"]
}

df = pd.DataFrame(data)

In [8]:
print(df)

     Food
0  Burger
1   Pizza
2  Burger
3   Pasta

In [9]:
encoded= pd.get_dummies(df["Food"],dtype=int)

In [10]:
print(encoded)

   Burger  Pasta  Pizza
0       1      0      0
1       0      0      1
2       1      0      0
3       0      1      0

In [11]:
print(encoded.shape[1])

3

In [13]:
print(encoded.iloc[1])

Burger    0
Pasta     0
Pizza     1
Name: 1, dtype: int64

In [15]:
df.corr(numeric_only=True)

Empty DataFrame
Columns: []
Index: []

In [16]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 22, None, 25, 30],
    "Salary": [20000, 25000, 30000, None, 50000],
    "Department": ["IT", "HR", "IT", "HR", "IT"]
}

df = pd.DataFrame(data)

In [17]:
print(df)

  Name   Age   Salary Department
0    A  20.0  20000.0         IT
1    B  22.0  25000.0         HR
2    C   NaN  30000.0         IT
3    D  25.0      NaN         HR
4    E  30.0  50000.0         IT

In [19]:
df.iloc[0:3]

  Name   Age   Salary Department
0    A  20.0  20000.0         IT
1    B  22.0  25000.0         HR
2    C   NaN  30000.0         IT

In [20]:
df.shape

(5, 4)

In [21]:
df.columns

Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')

In [22]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2  False   True   False       False
3  False  False    True       False
4  False  False   False       False

In [23]:
df.isnull().sum()

Name          0
Age           1
Salary        1
Department    0
dtype: int64

In [24]:
df[df["Salary"]>25000]

  Name   Age   Salary Department
2    C   NaN  30000.0         IT
4    E  30.0  50000.0         IT

In [28]:
df.groupby("Department")["Salary"].mean()

Department
HR    25000.000000
IT    33333.333333
Name: Salary, dtype: float64

In [33]:
df["Bonus"]= df["Salary"]*0.05

In [34]:
df["Bonus"]

0    1000.0
1    1250.0
2    1500.0
3       NaN
4    2500.0
Name: Bonus, dtype: float64

In [35]:
df

  Name   Age   Salary Department   Bonus
0    A  20.0  20000.0         IT  1000.0
1    B  22.0  25000.0         HR  1250.0
2    C   NaN  30000.0         IT  1500.0
3    D  25.0      NaN         HR     NaN
4    E  30.0  50000.0         IT  2500.0

In [42]:
df.fillna({
    "Age":df["Age"].mean(),
    "Salary" : df["Salary"].mean(),
    "Bonus" : df["Bonus"].mean()
        },inplace=True)

In [43]:
df

  Name    Age   Salary Department   Bonus
0    A  20.00  20000.0         IT  1000.0
1    B  22.00  25000.0         HR  1250.0
2    C  24.25  30000.0         IT  1500.0
3    D  25.00  31250.0         HR  1562.5
4    E  30.00  50000.0         IT  2500.0

In [44]:
df.to_csv("update.csv",index=False)

In [45]:
df

  Name    Age   Salary Department   Bonus
0    A  20.00  20000.0         IT  1000.0
1    B  22.00  25000.0         HR  1250.0
2    C  24.25  30000.0         IT  1500.0
3    D  25.00  31250.0         HR  1562.5
4    E  30.00  50000.0         IT  2500.0